MIN_PASSWORD_LENGTH = 8
STRONG_PASSWORD_LENGTH = 12

STRENGTH_WEAK = "Weak"
STRENGTH_MEDIUM = "Medium"
STRENGTH_STRONG = "Strong"

FINDING_SHORT_PASSWORD = "SHORT_PASSWORD"
FINDING_NO_UPPERCASE = "NO_UPPERCASE"
FINDING_NO_NUMBER = "NO_NUMBER"
FINDING_NO_SYMBOL = "NO_SYMBOL"